export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const TENANT_REPOSITORY = Symbol('TENANT_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const TENANT_MEMBERSHIP_REPOSITORY = Symbol('TENANT_MEMBERSHIP_REPOSITORY');
export const ENCRYPTION_SERVICE = Symbol('ENCRYPTION_SERVICE');
